# Generated by Django 4.2.5 on 2023-12-14 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_user_avatar_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='query',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('No Category Listed', 'No category'), ('Fashion', 'Fashion'), ('History', 'History'), ('School', 'School')], default='No Category Listed', max_length=18),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
