# Generated by Django 4.2.5 on 2024-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_game_alter_quiz_category_player_markedquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='question',
            field=models.IntegerField(default=0),
        ),
    ]
