# Generated by Django 4.2.5 on 2024-02-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_remove_player_question_alter_markedquestion_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedquestion',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked', to='quizzes.game'),
        ),
    ]
