# Generated by Django 4.2.5 on 2024-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_markedquestion_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='show_correct_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='show_player_answers',
            field=models.BooleanField(default=False),
        ),
    ]
