# Generated by Django 4.2.5 on 2024-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_game_show_correct_answers_game_show_player_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='show_correct_answers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='show_player_answers',
            field=models.BooleanField(default=True),
        ),
    ]
